# ── RENDER (PostgreSQL) ────────────────────────────────
spring.datasource.url=jdbc:postgresql://abhinav:TOqmqpCvDzuoYckOlmP1DEkFybQPOKsc@dpg-d6qit6fgi27c73a474p0-a.oregon-postgres.render.com/expensetrackerdb_dan8
spring.datasource.username=$abhinav
spring.datasource.password=TOqmqpCvDzuoYckOlmP1DEkFybQPOKsc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
logging.level.com.expensetracker=INFO
logging.level.org.springframework.security=WARN
